### PR TITLE
Technical Test Related Pull Requests

### PR DESCRIPTION
**Pull request by hairychris**
First things first: Update Django to latest release in 1.7 series (1.7.11)

Whilst this version is still unsupported and we will still need
to move to a newer version this will fix a few security issues.

Update tox config from django171 to django1711

For more information on django 1.7 security releases please see:
https://docs.djangoproject.com/en/1.7/releases/security/

All work was performed on a feature branch and then merged to develop. It would usually have gone through a review process by the time this happened. I could have pushed the feature-branch to enable this.

```
Summary of actions:
- The feature branch 'feature/django-security-update' was merged into 'develop'
- Feature branch 'feature/django-security-update' has been removed
- You are now on branch 'develop'
```

### CODE REVIEW

**Comment by hugorodgerbrown** [comment]
Thanks @hairychris - going to close the PR so it's not hanging around, and will review and get back to you.

**Comment by hairychris** [comment]
@hugorodgerbrown thanks, please don't review yet I've still got to merge a feature branch. I'll post here when that's done. =)

**Comment by hairychris** [comment]
I have merged the feature branch and pushed, it's not showing here as the pull request is closed. Feel free to check it out on my profile though.

**Comment by hugorodgerbrown** [comment]
:thumbsup:

**Pull request closed without merging**
